services:

  db:
    image: mariadb:10.6
    restart: always
    container_name: ctr_dotnet_db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - vol_dotnet_db:/var/lib/mysql
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_PORT}"
    networks:
      - net_donet_bridge

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    container_name: ctr_dotnet_phpmyadmin
    ports:
      - "${PMY_EXTERNAL_PORT}:${PMY_PORT}"
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_TIMEOUT=43200 
      - PMA_IDLE_TIMEOUT=43200    
    depends_on:
      - db
    networks:
      - net_donet_bridge

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: img_dotnet_mvc:1.0
    container_name: ctr_dotnet_app
    ports:
      - "5000:80"
    volumes:
      - ./app:/app:rw
    working_dir: /app
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
    stdin_open: true
    tty: true
    user: "1000:1000"  # ← Forzar que el contenedor use el UID y GID correctos
    networks:
      - net_donet_bridge

networks:
  net_donet_bridge:
    name: net_donet_bridge
    driver: bridge

volumes:
  vol_dotnet_db:
    name: vol_dotnet_db


      
    #environment:
    #  - ASPNETCORE_ENVIRONMENT=Development
    #  - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MiBaseDeDatos;User Id=sa;Password=TuPasswordSeguro;TrustServerCertificate=True;
    #depends_on:
    #  - sqlserver

  #sqlserver:
  #  image: mcr.microsoft.com/mssql/server:2022-latest
  #  container_name: mi_proyecto_sqlserver
  #  ports:
  #    - "1433:1433"
  #  environment:
  #    - ACCEPT_EULA=Y
  #    - SA_PASSWORD=TuPasswordSeguro
  #  volumes:
  #    - sqlserver_data:/var/opt/mssql

#volumes:
#  sqlserver_data:
