services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ctr_aspdotnet
    ports:
      - "5000:80"
    volumes:
      - ./app:/app

    working_dir: /app
    stdin_open: true
    tty: true
    #environment:
    #  - ASPNETCORE_ENVIRONMENT=Development
    #  - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MiBaseDeDatos;User Id=sa;Password=TuPasswordSeguro;TrustServerCertificate=True;
    #depends_on:
    #  - sqlserver

  #sqlserver:
  #  image: mcr.microsoft.com/mssql/server:2022-latest
  #  container_name: mi_proyecto_sqlserver
  #  ports:
  #    - "1433:1433"
  #  environment:
  #    - ACCEPT_EULA=Y
  #    - SA_PASSWORD=TuPasswordSeguro
  #  volumes:
  #    - sqlserver_data:/var/opt/mssql

#volumes:
#  sqlserver_data:
