services:
  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    image: img_mvc_dotnet:1.0
    container_name: ctr_mvc_dotnet
    ports:
      - "5000:80"
    volumes:
      - ./app:/app:rw
    working_dir: /app
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    stdin_open: true
    tty: true
    user: "1000:1000"  # ← Forzar que el contenedor use el UID y GID correctos
    #environment:
    #  - ASPNETCORE_ENVIRONMENT=Development
    #  - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MiBaseDeDatos;User Id=sa;Password=TuPasswordSeguro;TrustServerCertificate=True;
    #depends_on:
    #  - sqlserver

  #sqlserver:
  #  image: mcr.microsoft.com/mssql/server:2022-latest
  #  container_name: mi_proyecto_sqlserver
  #  ports:
  #    - "1433:1433"
  #  environment:
  #    - ACCEPT_EULA=Y
  #    - SA_PASSWORD=TuPasswordSeguro
  #  volumes:
  #    - sqlserver_data:/var/opt/mssql

#volumes:
#  sqlserver_data:
